### ISSUE TITLE
clic / drag event is based on frames not time.

### ISSUE THREAD

**Issue by Bowarc** [NemuiSen/ggez-egui#5]
Hey, im making a game with ggez and i wanted to add a gui crate to make some ui.

but i found a weird bug where when i don't limit my game's fps the egui's button clics are not register'd correctly.
I played a bit with it and i found that when i limit my fps, clics are register'd correctly.

I think the timing window where clics are not held enough to be drag event is based on number of frames between press and release.
that leaves a bug where high fps makes the clic event timing window so short that it's not user friendly

is there a way to fix this without re-writing the egui's code ?

**Comment by NemuiSen** [comment]
can you specify how the clicks are not registered correctly?, and if possible, a video or code that replicates the problem.

**Comment by Bowarc** [comment]
> 

Sure,
If the time between the press and the release is more than x frames the clic is considered a drag event and not register'd as a clic event. at least it's what i understood when playing with this 'bug'.
the problem with this method is that with high fps the timing window is very short, so short that it's not user friendly.

in depth explain, (may not be exact):
I don't know the correct number, but let's say that the time between the press and release M1 is 10 frames to be register'd as a clic event and not drag event, the problem is that this method is good for low fps(<200). but with high fps, 10 frames is a rly short amount of time, therefore not eazy to use

https://user-images.githubusercontent.com/63136904/154392017-a0c6599d-e2fa-41a5-b913-93d64a17bc77.mp4

**Comment by Bowarc** [comment]
I was able to recreate this bug by disabling vsync on the scale_factor.rs example
replace `let cb = ggez::ContextBuilder::new("game_id", "author")` by `let cb = ggez::ContextBuilder::new("game_id", "author").window_setup(ggez::conf::WindowSetup::default().vsync(false));` line 86.

**Comment by Bowarc** [comment]
Well, found a fix, a quite bad one tho...

Using drag event as click event.

**Comment by NemuiSen** [comment]
unfortunately I couldn't recreate the bug, but I think I found the source of the problem, I created a new branch that probably solves it, try it and tell me the results.
https://github.com/NemuiSen/ggez-egui/tree/input-dt

**Comment by Bowarc** [comment]
I tried it, both the example and on my project, it's working as expected.

Thanks!

**Comment by NemuiSen** [comment]
Cool, tomorrow i will merge input-dt to master and publish the new viersion
